# Generated by Django 5.2.9 on 2026-02-27 14:09

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself, your background, and the projects you want to build!'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a professional photo or avatar.', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='e.g., Python, React, Data Analysis', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
