# Generated by Django 5.2.9 on 2026-02-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Optional: Enter your Gemini API Key to enable AI task generation and chat summaries.', max_length=255, null=True),
        ),
    ]
