# Generated by Django 5.2.9 on 2026-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Optional: Enter your Gemini API Key to enable AI task generation.', max_length=255, null=True),
        ),
    ]
